//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientePlan
    {
        public int IDClientePlan { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public Nullable<int> IDPlan { get; set; }
        public string Mes { get; set; }
        public string Dia { get; set; }
        public Nullable<int> Año { get; set; }
        public string Autorizado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Planes Planes { get; set; }
    }
}
